### ISSUE TITLE
Error logging when beanstalkd unexpectedly stops?

### ISSUE THREAD

**Issue by Repox** [kr/beanstalkd#229]
I've experienced that beanstalkd has suddenly stopped it's service on my Ubuntu 13.10.
I can't find any error log - is is possible to enable logging?

**Comment by jonathanpmartins** [comment]
I will logging too :+1:

**Comment by teddychan** [comment]
any plan to add this?

**Comment by kr** [comment]
There is a flag `-v` that causes beanstalkd to be more verbose on stdout. You can give it multiple times to increase the verbosity. If you want to save the log, you can redirect stdout to a file or pipe it to a log rotation utility.

**Comment by kr** [comment]
I think this should answer the original question. If not, feel free to reopen this or open a new issue! :)

**Comment by Repox** [comment]
@kr, as much as I appreciate alternative solutions when none is available, this seems to be a really bad solution. General logging is a minimum requirement for me to use this in a production environment. 

I like beanstalkd for it simplicity, but the lack of proper logging has forced me to use a more complex solution (RabbitMQ). 

I'm sad to hear that a workaround seems sufficient.

**Comment by kr** [comment]
I apologize, I don't know your definition of "proper" logging.

Beanstalkd provides a logging facility, not a workaround, on stdout. If you want to use syslog to sort and rotate log files, you can run beanstalkd with a pipe to the standard `logger` program:

```
beanstalkd -v | logger -t beanstalkd
```

There are other log rotation and log handling utilities available, some built in to the OS, some as third-party additions, but the task of managing log files is best done by a dedicated tool, not beanstalkd.

**Comment by sijones-uk** [comment]
@kr I've been struggling to get this working. The verbosity switch seems to be `-V` rather than `-v`, but if I append `-V | logger -t beanstalkd` to my BEANSTALKD_EXTRA options in the `/etc/default/beanstalkd` config file and then restart Beanstalkd, I get the following error in the logs (and Beanstalkd fails to start):

```
beanstalkd[28955]: /usr/bin/beanstalkd: unknown argument: |
```

**Comment by JensRantil** [comment]
@sijones-uk That's not a problem with beanstalkd, but rather with your beanstalkd package in your dist. More init systems (Upstart, systemd) will take care of collecting the output of your applications and storing them in some log files, so you should generally not need `logger`.

**Comment by sijones-uk** [comment]
Please could you clarify "your beanstalkd package in your dist"? I was trying to implement the suggestion above, i.e. piping the output, but the error in the log suggests that the pipe character is unrecognized in this context.

**Comment by JensRantil** [comment]
> "your beanstalkd package in your dist"

This Github project doesn't have any code to package the Beanstalkd application in a Debian (`*.deb`) package or an RPM package or something like this. Those packages are generally the ones that creates the `/etc/default/beanstalkd` file. They are also the ones that configures the process manager (Upstart, systemd etc.) how to start/run `beanstalkd`. TLDR; Your problem is a "system administrator" problem, not a problem that can be solved by changing any code in this project. I suggest you find a Linux distribution mailing list or post on StackOverflow about what you want to do.
