### ISSUE TITLE
Who needs beanstalkd windows version. Some people demand it?

### ISSUE THREAD

**Issue by caidongyun** [kr/beanstalkd#267]
Who needs beanstalkd windows version. Some people demand it?
A version changed address here:  https://github.com/caidongyun/beanstalkd-win

**Comment by ghprod** [comment]
nice, i'll try it :)

Thanks

**Comment by ghprod** [comment]
how to install it?

**Comment by caidongyun** [comment]
cygwin automake  gcc

**Comment by caidongyun** [comment]
https://github.com/caidongyun/beanstalkd-win/blob/master/beanstalkd.exe

**Comment by ghprod** [comment]
I'm sorry for late reply ..

Thanks a lot for your respon .. cheers :+1:

**Comment by caidongyun** [comment]
iocp branch had maked

https://github.com/LomoX-Offical/beanstalkd-win/tree/iocp

**Comment by divmgl** [comment]
+1 on this, been wanting to try beanstalkd on Windows

**Comment by kr** [comment]
Hi @caidongyun! This is a great contribution. Do you plan to maintain your fork indefinitely? That would be ideal for me. (It would be difficult for me to do ongoing maintenance on a codebase that works on windows, because I don't have a good way to test anything. I would probably break something and not notice.)

I added a link to your port in the wiki: https://github.com/kr/beanstalkd/wiki/Windows-Support. Feel free to edit that page (or the rest of the wiki) if you need to make any corrections or updates.

Hopefully the wiki link will be good enough for people to find, so I'll go ahead and close this issue.

**Comment by insinfo** [comment]
@caidongyun

Do you have any pre-compiled binary for windows? If not, how can I compile it for windows? What version of Cygwin do I need? Do you have a step by step tutorial?

**Comment by insinfo** [comment]
I tried to run automake on Cygwin 2.919 64 bit but I'm getting these errors

```console
isaque@DESKTOP-HSDKQJ5 /cygdrive/c/beanstalkd/beanstalkd-win
$ automake
configure.ac:34: warning: AC_FUNC_WAIT3: `wait3' has been removed from POSIX.
configure.ac:34: Remove this `AC_FUNC_WAIT3' and adjust your code to use `waitpid' instead.
/mnt/share/cygpkgs/autoconf2.7/autoconf2.7.noarch/src/autoconf-2.71/lib/autoconf/functions.m4:2053: AC_FUNC_WAIT3 is expanded from...
configure.ac:34: the top level
configure.ac:32: error: required file './config.guess' not found
configure.ac:32:   'automake --add-missing' can install 'config.guess'
configure.ac:32: error: required file './config.sub' not found
configure.ac:32:   'automake --add-missing' can install 'config.sub'
```

**Comment by divmgl** [comment]
> Do you have any pre-compiled binary for windows? If not, how can I compile it for windows? What version of Cygwin do I need? Do you have a step by step tutorial?

You'll likely get better results just using a Linux container tbh.
