### ISSUE TITLE
CI issue

### ISSUE THREAD

**Issue by JensRantil** [kr/beanstalkd#317]
Some builds are simply pending. Not sure if this is a beanstalkd issue or Travis CI issue. See screenshot: 
<img width="794" alt="screen shot 2016-04-06 at 03 25 36" src="https://cloud.githubusercontent.com/assets/730342/14303046/5b4f2154-fba7-11e5-8c0e-570f7180121a.png">

**Comment by kr** [comment]
This is normal. They will get a status if anyone pushes new commits or rebases them. They all need to be rebased anyway.

**Comment by JensRantil** [comment]
@kr Yes, but it shouldn't be in this state [for two days](#316), right? I think this is still an issue.

**Comment by kr** [comment]
No. It's fine. I don't think travis is expected to suddenly run dozens of test runs because I added it to the project. If we didn't have [branch protection](https://github.com/blog/2051-protected-branches-and-required-status-checks) turned on, then these PRs would simply have no build status at all (there would be no dot). But since travis is a required status check, those PRs are yellow because what else would they be? They haven't passed, so they can't be merged. And they haven't failed either. So they must be pending.

**Comment by JensRantil** [comment]
Cool. Let's wait and see if they get run then. :+1:
